#!/usr/bin/env python3

from gi.repository import GLib
import locale
import os

samples = { 'C':  "Samples",
            'ar': "عينات",
            'fr': "Exemples",
            'es': "Ejemplos",
            'pt': "Amostras" }

media_dir="/var/endless-content"

def get_samples(locale):
    if locale in samples:
        return samples[locale]

    generic_locale = locale.split("_")[0]
    if generic_locale == locale:
        return samples['C']
    else:
        return get_samples(generic_locale)
    

def update_dir_link(orig, dest, new_locale):
    samples_file = os.path.join(dest, ".samples")
    if os.path.islink(samples_file):
        current_dir = os.readlink(samples_file)
        if not os.path.isabs(current_dir):
            current_dir = os.path.join(dest, current_dir)
        if os.path.islink(current_dir):
            os.remove(current_dir)
    else:
        return

    new_dir = os.path.join(dest, get_samples(new_locale))
    if os.path.exists(new_dir):
        return

    os.remove(samples_file)
    os.symlink(orig, new_dir)
    os.symlink(new_dir, samples_file)


new_locale = locale.getdefaultlocale()[0]

update_dir_link(os.path.join(media_dir, "music"), GLib.get_user_special_dir(GLib.USER_DIRECTORY_MUSIC), new_locale)
update_dir_link(os.path.join(media_dir, "pictures"), GLib.get_user_special_dir(GLib.USER_DIRECTORY_PICTURES), new_locale)
update_dir_link(os.path.join(media_dir, "videos"), GLib.get_user_special_dir(GLib.USER_DIRECTORY_VIDEOS), new_locale)

